### ISSUE TITLE
Version 1.4 not publicly available

### ISSUE THREAD

**Issue by shillshocked** [jhdscript/nzbliteclient#2]
New NzbLiteClient version detected: 1.4.0.0 (current: 1.2.0.0). Please visit https://www.nzblite.com to download the latest version.

Latest version downloadable is 1.2.

**Comment by jhdscript** [comment]
Hello,

you can find it here: https://github.com/jhdscript/nzbliteclient/releases

Regards

**Comment by shillshocked** [comment]
Yeah, I just found that, thanks. Should update the main nzblite download link to the current release.
